### PR TITLE
Zero the stack after AVX-512 XTS

### PR DESCRIPTION
**Pull request by pittma**
### Description of changes: 
A small patch to zero out the used stack frames in the AVX-512 XTS implementation.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license.

### CODE REVIEW

**Comment by nebeid** [comment]
Thank you, Dan @pittma.
I believe we could add:
- clearing the locations on the stack where the registers were backed up, taking into account the extra ones in the case of `win64`. This is done in `aesni-x86_64.pl`
- this change and the suggestion above to the decryption function.

**Comment by pittma** [comment]
As far as I can tell, this CI failure is unrelated. It looks like `HEAD` moved a few hours ago for the tpm2 dependency in this test, and now there is a conflict with the patch:

```
commit 84ead1b7a35362d5fae9b26a0edb9a68eeb6e5c8 (HEAD -> master, origin/master, origin/HEAD)
Author: Juergen Repp <juergen_repp@web.de>
Date:   Tue Jan 23 12:00:45 2024 +0100

    FAPI: Clean command context before execution.
    
    The FAPI command context now is cleared in the async function of
    every command.
    
    Signed-off-by: Juergen Repp <juergen_repp@web.de>
```

This is the error I'm seeing:

```sh
$ git apply /home/dpitt/src/aws-lc/tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
error: patch failed: test/unit/fapi-eventlog.c:138
error: test/unit/fapi-eventlog.c: patch does not apply
```

**Comment by torben-hansen** [comment]
> As far as I can tell, this CI failure is unrelated. It looks like `HEAD` moved a few hours ago for the tpm2 dependency in this test, and now there is a conflict with the patch:
> 
> ```
> commit 84ead1b7a35362d5fae9b26a0edb9a68eeb6e5c8 (HEAD -> master, origin/master, origin/HEAD)
> Author: Juergen Repp <juergen_repp@web.de>
> Date:   Tue Jan 23 12:00:45 2024 +0100
> 
>     FAPI: Clean command context before execution.
>     
>     The FAPI command context now is cleared in the async function of
>     every command.
>     
>     Signed-off-by: Juergen Repp <juergen_repp@web.de>
> ```
> 
> This is the error I'm seeing:
> 
> ```shell
> $ git apply /home/dpitt/src/aws-lc/tests/ci/integration/tpm2_tss_patch/aws-lc-tpm2-tss.patch
> error: patch failed: test/unit/fapi-eventlog.c:138
> error: test/unit/fapi-eventlog.c: patch does not apply
> ```

Resolved here: https://github.com/aws/aws-lc/pull/1422

**Comment by nebeid** [comment]
I think the comments that used to be there before line 1881 for the special case of zeroising were helpful:
```
# Stack usage isn't divisible by 64, so we use a kmask register to
# only use 48 of the bytes (6 quad-words).
```
The prior comments were good too.

**Comment by pittma** [comment]
> I think the comments that used to be there before line 1881 for the special case of zeroising were helpful:
> 
> ```
> # Stack usage isn't divisible by 64, so we use a kmask register to
> # only use 48 of the bytes (6 quad-words).
> ```
> 
> The prior comments were good too.

Thanks for saying so @nebeid. I'd mostly left them as mnemonics for myself and I began to fear I was the only one! I've added them back.

**Review by nebeid — APPROVED** [review]

**Review by dkostic — APPROVED** [review]

**Pull request merged**
