### PR TITLE
Add GitHub Action for testing commits with aws-lc-rs

### PR DESCRIPTION
**Pull request by skmcgrail**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and 
the ISC license.

### CODE REVIEW

**Review by justsmth — APPROVED** [review]

**Review by justsmth — APPROVED** [review]

**Comment by torben-hansen** [comment]
`.github/workflows/aws-lc-rs.yml / standard (pull_request)`

Where does the name come from? Not that descriptive.

**Comment by skmcgrail** [comment]
> `.github/workflows/aws-lc-rs.yml / standard (pull_request)`
> 
> Where does the name come from? Not that descriptive.

Was using `run-name` instead of `name`, fixed.

**Review by justsmth — APPROVED** [review]

**Review by samuel40791765 — APPROVED** [review]
Would there be value in adding a similar action for aws-lc-fips-sys?

**Comment by skmcgrail** [comment]
> Would there be value in adding a similar action for aws-lc-fips-sys?

Yup I was planning to add a check on the FIPS branch specifically for that.

**Pull request merged**
