### PR TITLE
Pull in the latest changes from s2n-bignum (2023-07-25) 

### PR DESCRIPTION
**Pull request by aqjune-aws**
### Issues:
N/A

### Description of changes: 
(2022-07-25) Pull in the latest changes from s2n-bignum.

The commands in the internal Quip document was used, with PATHS_TO_KEEP defined as follows:
```
PATHS_TO_KEEP="./arm/p384 ./x86_att/p384 ./arm/p521 ./x86_att/p521 ./x86_att/curve25519/curve25519_x25519.S ./x86_att/curve25519/curve25519_x25519base.S ./x86_att/curve25519/curve25519_x25519_alt.S ./x86_att/curve25519/curve25519_x25519base_alt.S  ./arm/curve25519/curve25519_x25519.S ./arm/curve25519/curve25519_x25519base.S ./arm/curve25519/curve25519_x25519_alt.S ./arm/curve25519/curve25519_x25519base_alt.S ./arm/curve25519/curve25519_x25519_byte.S ./arm/curve25519/curve25519_x25519base_byte.S ./arm/curve25519/curve25519_x25519_byte_alt.S ./arm/curve25519/curve25519_x25519base_byte_alt.S ./arm/fastmul/bignum_emontredc_8n.S ./arm/fastmul/bignum_kmul_16_32.S ./arm/fastmul/bignum_kmul_32_64.S ./arm/fastmul/bignum_ksqr_16_32.S ./arm/fastmul/bignum_ksqr_32_64.S ./arm/generic/bignum_ge.S ./arm/generic/bignum_mul.S ./arm/generic/bignum_optsub.S ./arm/generic/bignum_sqr.S ./include/_internal_s2n_bignum.h"
```

### Call-outs:
Point out areas that need special attention or support during the review process. Discuss architecture or design changes.

### Testing:
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps to be verified by the reviewer?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license.

### CODE REVIEW

**Comment by aqjune-aws** [comment]
The ultimate change is in this draft PR: https://github.com/aws/aws-lc/pull/1108/files
This PR splits it and upstreams assemblies in s2n-bignum that use non-NEON instructions.

**Review by nebeid — APPROVED** [review]

**Comment by aqjune-aws** [comment]
Upstreamed to the head of the main branch

**Comment by nebeid** [comment]
To be merge NO SQUASH.

**Comment by aqjune-aws** [comment]
@skmcgrail Hi, may I ask for your review, please?

**Review by skmcgrail — APPROVED** [review]

**Comment by aqjune-aws** [comment]
The required CI runs have finished successfully, after merging to the latest main branch!
Could anyone merge this PR, please?

**Pull request merged**
