### PR TITLE
Add support for LoongArch.

### PR DESCRIPTION
**Pull request by liuxiang88**
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

### CODE REVIEW

**Comment by samuel40791765** [comment]
Sorry about the confusing x86 failure, but you'll need to rebase your changes off of our current main branch. Once that's done, the `aws-lc-ci-linux-x86` CI should be passing through. Thanks for the contribution :)!

**Comment by liuxiang88** [comment]
Hi @samuel40791765 ,
Thank you so much for reminding me.Now the aws-lc-ci-linux-x86 CI is ok.

**Comment by skmcgrail** [comment]
Hey @liuxiang88, we are willing to take this change to support compilation on LoongArch, but don't currently have the CI infrastructure in place to continually test and validate that the library compiles and passes tests.

Would you be able to demonstrate/show the CMake build output and include a log here of the `crypto_test` target execution to give us visibility into the tests passing? We will work to added testing to our workflow as a separate action item, but we don't want to block your PR on delivery of that. 

Additionally if you have any information / resources you could share regarding cross-compiling for LoongArch and testing with either Docker or QEMU that would be appreciated. Thanks!

**Comment by liuxiang88** [comment]
1. CMake build output:

`[loongson@localhost aws-lc-build]$ ls -lrt
总用量 72712
-rw-rw-r-- 1 loongson loongson    15547 9月   1 16:08 embed_test_data_args.txt
drwxrwxr-x 3 loongson loongson     4096 9月   1 16:08 util
-rw-rw-r-- 1 loongson loongson    21390 9月   1 16:08 CMakeCache.txt
-rw-rw-r-- 1 loongson loongson     2341 9月   1 16:08 cmake_install.cmake
drwxrwxr-x 7 loongson loongson     4096 9月   1 16:08 CMakeFiles
-rw-rw-r-- 1 loongson loongson   598129 9月   1 16:08 build.ninja
-rw-rw-r-- 1 loongson loongson 56516516 9月   1 16:09 crypto_test_data.cc
-rw-rw-r-- 1 loongson loongson 17262194 9月   1 16:09 libboringssl_gtest.a
drwxrwxr-x 5 loongson loongson     4096 9月   1 16:10 crypto
drwxrwxr-x 4 loongson loongson     4096 9月   1 16:11 ssl
drwxrwxr-x 3 loongson loongson     4096 9月   1 16:11 tool
-rw-rw-r-- 1 loongson loongson     5049 9月   1 16:12 install_manifest.txt
`

2.  test result
`[400/409] cd /home/loongson/aws-lc && cd ssl/test/runner && /usr/bin/go test -timeout...sfer-test-file /home/loongson/aws-lc/ssl/test/runner/ssl_transfer/test_case_names.txt
0/0/968/1000/8886
0/0/968/1000/8886
0/0/968/1000/8886
0/0/968/1000/8886
0/0/969/1000/8886
0/0/969/1000/8886
0/0/1968/2000/8886
0/0/1969/2000/8886
0/0/2968/3000/8886
0/0/2969/3000/8886
0/0/3968/4000/8886
0/0/3969/4000/8886
0/0/4968/5000/8886
0/0/4969/5000/8886
0/0/5968/6000/8886
0/0/5968/6000/8886
0/0/5968/6000/8886
0/0/5969/6000/8886
0/0/6968/7000/8886
0/0/6968/7000/8886
0/0/6968/7000/8886
0/0/6968/7000/8886
0/0/6969/7000/8886
0/0/7968/8000/8886
0/0/7968/8000/8886
0/0/7968/8000/8886
0/0/7969/8000/8886
0/0/8886/8886/8886

PASS
ok  	boringssl.googlesource.com/boringssl/ssl/test/runner	11.302s
[408/409] cd /home/loongson/aws-lc && /usr/bin/go test ./ssl/test/runner/hpke ./util/ar && /usr/bin/go run util/all_tests.go -build-dir /home/loongson/aws-lc-build
ok  	boringssl.googlesource.com/boringssl/ssl/test/runner/hpke	0.229s
ok  	boringssl.googlesource.com/boringssl/util/ar	0.003s
crypto/crypto_test [shard 19/32]
crypto/crypto_test [shard 9/32]
crypto/crypto_test --gtest_also_run_disabled_tests --gtest_filter=RSATest.DISABLED_BlindingCacheConcurrency
crypto/urandom_test
crypto/crypto_test --fork_unsafe_buffering --gtest_filter=RandTest.*:-RandTest.Fork
crypto/crypto_test --gtest_filter=RandTest.* (custom environment)
crypto/crypto_test [shard 24/32]
crypto/crypto_test [shard 25/32]
crypto/crypto_test --gtest_filter=ForkDetect.* (custom environment)
crypto/crypto_test [shard 16/32]
ssl/ssl_test [shard 2/32]
ssl/ssl_test [shard 1/32]
ssl/ssl_test [shard 3/32]
ssl/ssl_test [shard 4/32]
ssl/ssl_test [shard 5/32]
ssl/ssl_test [shard 6/32]
crypto/crypto_test [shard 22/32]
ssl/ssl_test [shard 7/32]
ssl/ssl_test [shard 8/32]
crypto/crypto_test [shard 7/32]
ssl/ssl_test [shard 10/32]
ssl/ssl_test [shard 9/32]
ssl/ssl_test [shard 11/32]
ssl/ssl_test [shard 12/32]
ssl/ssl_test [shard 13/32]
ssl/ssl_test [shard 14/32]
ssl/ssl_test [shard 16/32]
ssl/ssl_test [shard 15/32]
ssl/ssl_test [shard 18/32]
ssl/ssl_test [shard 19/32]
ssl/ssl_test [shard 20/32]
ssl/ssl_test [shard 17/32]
crypto/crypto_test [shard 18/32]
ssl/ssl_test [shard 24/32]
crypto/crypto_test [shard 29/32]
ssl/ssl_test [shard 28/32]
crypto/crypto_test [shard 8/32]
ssl/ssl_test [shard 31/32]
crypto/crypto_test [shard 23/32]
ssl/ssl_test [shard 29/32]
crypto/mem_test
crypto/mem_set_test
crypto/dynamic_loading_test
ssl/ssl_test [shard 30/32]
crypto/crypto_test [shard 26/32]
ssl/ssl_test [shard 32/32]
crypto/crypto_test [shard 31/32]
ssl/ssl_test [shard 23/32]
crypto/crypto_test [shard 17/32]
ssl/ssl_test [shard 21/32]
ssl/ssl_test [shard 22/32]
crypto/crypto_test [shard 28/32]
ssl/ssl_test [shard 26/32]
ssl/ssl_test [shard 25/32]
ssl/ssl_test [shard 27/32]
crypto/crypto_test [shard 15/32]
crypto/crypto_test [shard 30/32]
crypto/crypto_test [shard 1/32]
crypto/crypto_test [shard 27/32]
crypto/crypto_test [shard 10/32]
crypto/crypto_test [shard 12/32]
crypto/crypto_test [shard 2/32]
crypto/crypto_test [shard 32/32]
crypto/crypto_test [shard 13/32]
crypto/crypto_test [shard 11/32]
crypto/crypto_test [shard 20/32]
crypto/crypto_test [shard 3/32]
crypto/crypto_test [shard 4/32]
crypto/crypto_test [shard 5/32]
crypto/crypto_test [shard 6/32]
crypto/crypto_test [shard 21/32]
crypto/crypto_test [shard 14/32]
crypto/crypto_test --gtest_also_run_disabled_tests --gtest_filter=BNTest.DISABLED_WycheproofPrimality

All tests passed!`

**Comment by justsmth** [comment]
I was finally able to get a cross-compile toolchain built for loongarch64. I can confirm that the build succeeds using that toolchain. (I'm still working on setting up a test environment.)

**Comment by justsmth** [comment]
I confirmed that our `crypto_test` and `ssl_test` succeed using Qemu emulation.

crypto_test:
```
...

[----------] Global test environment tear-down
[==========] 1681 tests from 105 test suites ran. (2348358 ms total)
[  PASSED  ] 1681 tests.

  YOU HAVE 3 DISABLED TESTS
```

ssl_test:
```
...

[----------] Global test environment tear-down
[==========] 540 tests from 10 test suites ran. (70862 ms total)
[  PASSED  ] 540 tests.

  YOU HAVE 1 DISABLED TEST

```

**Review by justsmth — APPROVED** [review]

**Review by skmcgrail — APPROVED** [review]

**Pull request merged**
