### PR TITLE
Update rsa service indicator test vectors in FIPS 2022 branch (#1230)

### PR DESCRIPTION
**Pull request by billbo-yang**
### Issues:
Addresses CryptoAlg-1838

### Description of changes: 
Moves changes from https://github.com/aws/aws-lc/pull/1230 into the FIPS 2022 branch

### Call-outs:
N/A

### Testing:
Tests passed locally

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license.

### CODE REVIEW

**Review by samuel40791765 — APPROVED** [review]

**Review by andrewhop — APPROVED** [review]

**Review by dkostic — APPROVED** [review]

**Comment by jvdsn** [comment]
What about updating https://github.com/aws/aws-lc/blob/fips-2022-11-02/crypto/fipsmodule/service_indicator/service_indicator.c#L188 ?

**Comment by billbo-yang** [comment]
> What about updating https://github.com/aws/aws-lc/blob/fips-2022-11-02/crypto/fipsmodule/service_indicator/service_indicator.c#L188 ?

The `EVP_DigestSignFinal()` API will fail and return false since our PSS with hashLen == saltLen, 1024-bit modulus, and SHA-512 is not possible for our implementation. As such, if we add a test vector for this situation and adjust `is_md_fips_approved_for_verifying` accordingly, our service indicator test will always fail.

You can see comments [here](https://github.com/aws/aws-lc/pull/1232/files#diff-ff3c1dd2d1224704ce9f4249523fbd553b13e40e9431607f3ee5489af2298358R1878) and also [here](https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/service_indicator/service_indicator_test.cc#L1893) that note that we don't support the capability in our implementation.

**Comment by jvdsn** [comment]
> The `EVP_DigestVerifyFinal()` API will fail and return false since our PSS with hashLen == saltLen, 1024-bit modulus, and SHA-512 is not possible for our implementation. As such, if we add a test vector for this situation and adjust `is_md_fips_approved_for_verifying` accordingly, our service indicator test will always fail.

It is not possible for a caller to request a saltLen != hashLen?

**Comment by billbo-yang** [comment]
> > The `EVP_DigestVerifyFinal()` API will fail and return false since our PSS with hashLen == saltLen, 1024-bit modulus, and SHA-512 is not possible for our implementation. As such, if we add a test vector for this situation and adjust `is_md_fips_approved_for_verifying` accordingly, our service indicator test will always fail.
> 
> It is not possible for a caller to request a saltLen != hashLen?

You can see in [EVP_DigestVerify_verify_service_indicator](https://github.com/aws/aws-lc/blob/bb1aabad676ccb61e195917452d8d90c86d73217/crypto/fipsmodule/service_indicator/service_indicator.c#L247) that if saltLen != hashLen, we return false.

**Comment by jvdsn** [comment]
> You can see in [EVP_DigestVerify_verify_service_indicator](https://github.com/aws/aws-lc/blob/bb1aabad676ccb61e195917452d8d90c86d73217/crypto/fipsmodule/service_indicator/service_indicator.c#L247) that if saltLen != hashLen, we return false.

Great, thanks!

**Pull request merged**
